Dmf 4868 remove UI test most visited pages
Jahia/qa-mf-unomi-api pull request #7
Opened 2021-08-13 07:59 UTC by ksagnard

2021-08-13 09:12 UTC, jkevan requested changes

2021-08-13 09:12 UTC, jkevan commented on src/main/java/org/jahia/test/unomiapi/helpers/EventHelper.java
> +        }
Actually the response is a Map<String, Long>.
So you could easily deserialize it using the object mapper like:

```
ObjectMapper objectMapper = new ObjectMapper();
TypeReference<HashMap<String, Long>> typeRef = new TypeReference<HashMap<String, Long>>() {};
Map<String, Long> response = objectMapper.readValue(this.unomiApiScenarioRuntimeData.getResponse().asString(), typeRef);
//read the map to get the value you are looking for.
```

2021-08-13 09:17 UTC, ksagnard commented on src/test/java/org/jahia/test/unomiapi/glue/EventSteps.java
> +    }
We just save it in a variable to have a comparison on the next step

2021-09-01 10:30 UTC, dgriffon commented on src/test/java/org/jahia/test/unomiapi/glue/EventSteps.java
> +    @Given("The number of view is 1 for page {string} by API with credentials {string} {string}")
Can you please have only one entry for 1 or 0 page view? Use the number as a parameter

2021-09-01 10:30 UTC, dgriffon commented on src/main/java/org/jahia/test/unomiapi/helpers/EventHelper.java
> +        String lookupKey = "";
set it to null and not empty value

2021-09-01 10:30 UTC, dgriffon commented on src/main/java/org/jahia/test/unomiapi/helpers/EventHelper.java
> +            return 0;
this can be simplified by 
`return lookupKey !=null ? Integer.parseInt(responseJson.get(lookupKey).toString()) : 0`

2021-09-01 12:10 UTC, dgriffon approved these changes

2021-09-01 12:17 UTC, merged